import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import {Router} from '@angular/router';
import {AccountService} from '../account.service';

@Component({
  selector: 'app-auth-form',
  templateUrl: './auth-form.component.html',
  styleUrls: ['./auth-form.component.css']
})
export class AuthFormComponent implements OnInit {
  codeIncorrect = false;
  code: number;
  count = 0;
  check: number;

  constructor(private router: Router,
              private accountService: AccountService) {}

  ngOnInit(): void {
    // Get code generated on backend to verify the code input by the user
    this.code = this.accountService.code;
    // Registration or authentication mode
    this.check = this.accountService.check;
    console.log(this.code);
  }

  // Method called upon form submission
  onSubmit(form: NgForm): void {
    // Check if form is valid
    if (!form.valid) {
      return;
    }
    // Check if the code provided by the user matches the code generated by the backend
    if (this.code === form.value.code) {
      // Registration mode
      if (this.check === 0) {
        // Redirect to CameraComponent to take user picture
        this.router.navigate(['/camera']);
        // Authentication mode
      } else if (this.check === 1) {
        // Call getToken() method to get the authentication token and create session cookie
        this.accountService.getToken();
      }
      // If the user inputs incorrect code
    } else {
      // To inform user that the code is incorrect
      this.codeIncorrect = true;
      // Count number of incorrect code inputs, after 3 attempts the user is redirected to Home screen
      this.count += 1;
      if (this.count === 3) {
        this.count = 0;
        this.router.navigate(['/']);
      }
      form.resetForm();
    }
  }
}
